In [ ]:
from google.colab import files
uploaded = files.upload()

Saving chronic disease.csv to chronic disease.csv

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# cancer disease duplicate data remove and merging two cancer dataset

In [ ]:
df1 = pd.read_csv('pubmed_ALL_cancer_environment_20251214_010208.csv', header=0, index_col=0)

In [ ]:
df2 = pd.read_csv('cancer.csv', header=0, index_col=0)

In [ ]:
df = pd.concat([df1, df2], ignore_index=True)

In [ ]:
df.head()

,Title,Abstract,Authors,Affiliation,Country,Journal,Year,DOI,URL
0,"Comprehensive study of radon levels, health ri...",Water quality assessment represents a fundamen...,Mohammad Qadr Hiwa; Farhad Salih Najeba; Amin ...,"Department of Physics, College of Science, Uni...",NaN,Regulatory toxicology and pharmacology : RTP,2026,NaN,https://pubmed.ncbi.nlm.nih.gov/41077261/
1,Participatory science to action: Radon literac...,Low radon testing rates in communities of colo...,Dai Dajun; Jelks Na'Taki Osborne; Smith Gwendy...,"Department of Geosciences, Georgia State Unive...",Usa,Journal of environmental radioactivity,2026,NaN,https://pubmed.ncbi.nlm.nih.gov/41130130/
2,Evaluating overestimated radon risk in predict...,Radon is recognised as the second most signifi...,Tejado-Ramos Juan-José; Alvarez-Toral Aitor; G...,Technological Institute of Ornamental Rocks an...,Spain,Journal of environmental radioactivity,2026,NaN,https://pubmed.ncbi.nlm.nih.gov/41187632/
3,The diagnostic potential of urinary volatile o...,Post-colonoscopy colorectal cancer (CRC) rates...,van Liere Elsa L S A; Ramsoekh Dewkoemar; Stew...,"Department of Gastroenterology and Hepatology,...",Uk,International journal of cancer,2026,NaN,https://pubmed.ncbi.nlm.nih.gov/40985860/
4,Organ-level radiation dose estimations from ca...,Children with congenital heart disease (CHD) u...,Wong-Siegel Jeannette R; Glatz Andrew C; Zampi...,New York-Presbyterian Morgan Stanley Children'...,NaN,"Radiation physics and chemistry (Oxford, Engla...",2026,NaN,https://pubmed.ncbi.nlm.nih.gov/40756629/

In [ ]:
df.shape

(72369, 9)

In [ ]:
def clean_text(text):
    if pd.isna(text):
        return ""
    return (
        str(text)
        .lower()
        .strip()
    )

df['title_clean'] = df['Title'].apply(clean_text)
df['abstract_clean'] = df['Abstract'].apply(clean_text)

In [ ]:
duplicates = df[
    df.duplicated(subset=['title_clean'], keep=False) |
    df.duplicated(subset=['abstract_clean'], keep=False)
]

print("Total duplicates found:", duplicates.shape[0])

Total duplicates found: 14858

In [ ]:
duplicates = df[
    df.duplicated(subset=['title_clean'], keep=False) |
    df.duplicated(subset=['abstract_clean'], keep=False)
]

print("Total duplicates found:", duplicates.shape[0])

Total duplicates found: 14858

In [ ]:
df_deduplicated = df.loc[
    ~(
        df.duplicated(subset=['title_clean'], keep='first') |
        df.duplicated(subset=['abstract_clean'], keep='first')
    )
]

In [ ]:
print("Before:", df.shape)
print("After:", df_deduplicated.shape)

Before: (72369, 11)
After: (64652, 11)

# *LUNG* disease duplicate data remove and merging two cancer dataset

In [ ]:
df_lung = pd.read_csv("lung.csv", header=0, index_col=0)

In [ ]:
df2_lung = pd.read_csv("pubmed_ALL_lung_environment_20251214_011723.csv", header=0, index_col=0)

In [ ]:
df_lung = pd.concat([df_lung, df2_lung], ignore_index=True)

In [ ]:
df_lung.head()

,Title,Abstract,Authors,Affiliation,Country,Journal,Year,DOI,URL
0,Long-term exposure to black carbon and inciden...,Air pollution is a known risk factor for chron...,Zhang Jiawei; So Rina; Bergmann Marie; Tuffier...,"Section of Environmental Health, Department of...",Sweden,Environmental research,2026,NaN,https://pubmed.ncbi.nlm.nih.gov/41265677/
1,"COPD Exacerbations, Air Pollutant Fluctuations...",Pandemic-era associations between air pollutan...,Mikaeeli Sahar; Doiron Dany; Bourbeau Jean; Li...,Respiratory Epidemiology and Clinical Research...,Canada,International journal of chronic obstructive p...,2025,NaN,https://pubmed.ncbi.nlm.nih.gov/40125072/
2,Overlapping exposure to cigarette smoke and pa...,NaN,Yan Lifeng; Guo Huaqi; Fu Juan; Zhou Tianyu,Department of Respiratory and Critical Care Me...,Usa,Chinese medical journal pulmonary and critical...,2025,NaN,https://pubmed.ncbi.nlm.nih.gov/40226604/
3,Exposure to living environmental risk factors ...,Chronic lung disease (CLD) imposes substantial...,Feng Yanmei; Qin Wei; Liao Rongqiang; Tang Fen...,"Department of Respiratory Medicine, Chongqing ...",China,BMC public health,2025,NaN,https://pubmed.ncbi.nlm.nih.gov/41034859/
4,Climate change-induced eco-anxiety and asthma ...,Pediatric asthma remains one of the most preva...,El-Sayed Mona Metwally; Al-Hrinat Jebril; Aldi...,"College of Nursing, Alexandria University, Ale...",China,Journal of pediatric nursing,2025,NaN,https://pubmed.ncbi.nlm.nih.gov/40816162/

In [ ]:
df_lung.shape

(20132, 9)

In [ ]:

def clean_text(text):
    if pd.isna(text):
        return ""
    return str(text).lower().strip()

df_lung['title_clean'] = df_lung['Title'].apply(clean_text)
df_lung['abstract_clean'] = df_lung['Abstract'].apply(clean_text)

duplicates = df_lung[
   df_lung.duplicated(subset=['title_clean'], keep=False) |
    df_lung.duplicated(subset=['abstract_clean'], keep=False)
]

print("Total duplicate rows found:", duplicates.shape[0])

df_lung_deduplicated = df_lung.loc[
    ~(
        df_lung.duplicated(subset=['title_clean'], keep='first') |
        df_lung.duplicated(subset=['abstract_clean'], keep='first')
    )
]

print("Rows before deduplication:", df_lung.shape[0])
print("Rows after deduplication:", df_lung_deduplicated.shape[0])

df_lung_deduplicated = df_lung_deduplicated.drop(
    columns=['title_clean', 'abstract_clean']
)



df_deduplicated.head()

Total duplicate rows found: 7013
Rows before deduplication: 20132
Rows after deduplication: 16570

,Title,Abstract,Authors,Affiliation,Country,Journal,Year,DOI,URL,title_clean,abstract_clean
0,"Comprehensive study of radon levels, health ri...",Water quality assessment represents a fundamen...,Mohammad Qadr Hiwa; Farhad Salih Najeba; Amin ...,"Department of Physics, College of Science, Uni...",NaN,Regulatory toxicology and pharmacology : RTP,2026,NaN,https://pubmed.ncbi.nlm.nih.gov/41077261/,"comprehensive study of radon levels, health ri...",water quality assessment represents a fundamen...
1,Participatory science to action: Radon literac...,Low radon testing rates in communities of colo...,Dai Dajun; Jelks Na'Taki Osborne; Smith Gwendy...,"Department of Geosciences, Georgia State Unive...",Usa,Journal of environmental radioactivity,2026,NaN,https://pubmed.ncbi.nlm.nih.gov/41130130/,participatory science to action: radon literac...,low radon testing rates in communities of colo...
2,Evaluating overestimated radon risk in predict...,Radon is recognised as the second most signifi...,Tejado-Ramos Juan-José; Alvarez-Toral Aitor; G...,Technological Institute of Ornamental Rocks an...,Spain,Journal of environmental radioactivity,2026,NaN,https://pubmed.ncbi.nlm.nih.gov/41187632/,evaluating overestimated radon risk in predict...,radon is recognised as the second most signifi...
3,The diagnostic potential of urinary volatile o...,Post-colonoscopy colorectal cancer (CRC) rates...,van Liere Elsa L S A; Ramsoekh Dewkoemar; Stew...,"Department of Gastroenterology and Hepatology,...",Uk,International journal of cancer,2026,NaN,https://pubmed.ncbi.nlm.nih.gov/40985860/,the diagnostic potential of urinary volatile o...,post-colonoscopy colorectal cancer (crc) rates...
4,Organ-level radiation dose estimations from ca...,Children with congenital heart disease (CHD) u...,Wong-Siegel Jeannette R; Glatz Andrew C; Zampi...,New York-Presbyterian Morgan Stanley Children'...,NaN,"Radiation physics and chemistry (Oxford, Engla...",2026,NaN,https://pubmed.ncbi.nlm.nih.gov/40756629/,organ-level radiation dose estimations from ca...,children with congenital heart disease (chd) u...

# Heart disease duplicate data remove and merging two cancer dataset

In [ ]:
df1_heart = pd.read_csv("pubmed_ALL_heart_environment_20251214_011142.csv", header=0, index_col=0)

In [ ]:
df2_heart = pd.read_csv("heart disese.csv", header=0, index_col=0)

In [ ]:
df_heart = pd.concat([df1_heart, df2_heart], ignore_index=True)
df_heart.shape

(31060, 14)

In [ ]:

def clean_text(text):
    if pd.isna(text):
        return ""
    return str(text).lower().strip()

df_heart['title_clean'] = df_heart['Title'].apply(clean_text)
df_heart['abstract_clean'] = df_heart['Abstract'].apply(clean_text)

duplicates = df_heart[
   df_heart.duplicated(subset=['title_clean'], keep=False) |
    df_heart.duplicated(subset=['abstract_clean'], keep=False)
]

print("Total duplicate rows found:", duplicates.shape[0])

df_heart_deduplicated = df_heart.loc[
    ~(
        df_heart.duplicated(subset=['title_clean'], keep='first') |
        df_heart.duplicated(subset=['abstract_clean'], keep='first')
    )
]

print("Rows before deduplication:", df_heart.shape[0])
print("Rows after deduplication:", df_heart_deduplicated.shape[0])

df_heart_deduplicated = df_heart_deduplicated.drop(
    columns=['title_clean', 'abstract_clean']
)



df_heart_deduplicated.head()

Total duplicate rows found: 4453
Rows before deduplication: 31060
Rows after deduplication: 28778

,Title,Abstract,Authors,Affiliation,Country,Journal,Year,DOI,URL,Keywords,Study_Type,Funding,PMC_ID,Timestamp
0,Therapeutic effects of Danhong injection on is...,"Danhong injection (DI), a standardized traditi...",Zeng Miaolin; Zhai Xiangyang; Zhang Man; Du Ha...,"School of Chinese Medicine, Wenzhou Medical Un...",China,Journal of ethnopharmacology,2026,NaN,https://pubmed.ncbi.nlm.nih.gov/41224089/,NaN,NaN,NaN,NaN,NaN
1,Targeting GALNT4 suppresses atherosclerosis vi...,Endothelial inflammation is a critical driver ...,Wei Pengcheng; Li Duan; Chen Wenxuan; Zhang Xi...,"School of Forensic Medicine, Xinxiang Medical ...",China,Cellular signalling,2026,NaN,https://pubmed.ncbi.nlm.nih.gov/41183695/,NaN,NaN,NaN,NaN,NaN
2,S<sup>2</sup>CAC: Semi-supervised coronary art...,Coronary artery calcium (CAC) scoring plays a ...,Hao Jinkui; Shah Nilay S; Zhou Bo,"Department of Radiology, Northwestern Universi...",Usa,Medical image analysis,2026,NaN,https://pubmed.ncbi.nlm.nih.gov/41045882/,NaN,NaN,NaN,NaN,NaN
3,Chewing tobacco use is associated with increas...,Arthroscopic rotator cuff repair (RCR) is a co...,Khnanisho Michael E; Holle Alejandro M; Tummal...,"Albany Medical College, Albany, NY, USA; Depar...",Usa,Journal of shoulder and elbow surgery,2026,NaN,https://pubmed.ncbi.nlm.nih.gov/40581083/,NaN,NaN,NaN,NaN,NaN
4,Association of obesity subphenotypes with indi...,Previous studies have reported that obesity-re...,He William J; Prescott Brenton R; Xanthakis Va...,"Framingham Heart Study, National Heart, Lung, ...",Usa,American heart journal,2026,NaN,https://pubmed.ncbi.nlm.nih.gov/41120039/,NaN,NaN,NaN,NaN,NaN

# Diabetes disease duplicate data remove and merging two cancer dataset

In [ ]:
df1_diabetes = pd.read_csv("diabetes.csv", header=0, index_col=0)

In [ ]:
df2_diabetes = pd.read_csv("pubmed_ALL_diabetes_environment_20251214_012014.csv", header=0, index_col=0)

In [ ]:
df_diabetes = pd.concat([df1_diabetes, df2_diabetes], ignore_index=True)
df_diabetes.shape

(5474, 14)

In [ ]:

def clean_text(text):
    if pd.isna(text):
        return ""
    return str(text).lower().strip()

df_diabetes['title_clean'] = df_diabetes['Title'].apply(clean_text)
df_diabetes['abstract_clean'] = df_diabetes['Abstract'].apply(clean_text)

duplicates = df_diabetes[
   df_diabetes.duplicated(subset=['title_clean'], keep=False) |
    df_diabetes.duplicated(subset=['abstract_clean'], keep=False)
]

print("Total duplicate rows found:", duplicates.shape[0])

df_diabetes_deduplicated = df_diabetes.loc[
    ~(
        df_diabetes.duplicated(subset=['title_clean'], keep='first') |
        df_diabetes.duplicated(subset=['abstract_clean'], keep='first')
    )
]

print("Rows before deduplication:", df_diabetes.shape[0])
print("Rows after deduplication:", df_diabetes_deduplicated.shape[0])

df_diabetes_deduplicated = df_diabetes_deduplicated.drop(
    columns=['title_clean', 'abstract_clean']
)



df_diabetes_deduplicated.head()

Total duplicate rows found: 424
Rows before deduplication: 5474
Rows after deduplication: 5255

,Title,Abstract,Authors,Affiliation,Country,Journal,Year,Keywords,Study_Type,Funding,DOI,PMC_ID,URL,Timestamp
0,Di-(2-ethylhexyl) phthalate exposure disrupts ...,"Di-(2-ethylhexyl) phthalate (DEHP), a widely u...","Shi, Dongxing; Wang, Xiaoman; Zhao, Yifei; Zha...","School of Public Health, Shanxi Medical Univer...",China,Toxicology,2026,Animals; Male; Diethylhexyl Phthalate; Insulin...,Journal Article,NaN,NaN,NaN,https://pubmed.ncbi.nlm.nih.gov/41101618/,2025-12-13 04:03:20
1,Short-term aircraft noise stress induces a fun...,Environmental stressors in the modern world ca...,"Marques, Jair G; Kuntic, Marin; Krishnankutty,...","Cancer Research UK Scotland Centre, University...",United States,The Science of the total environment,2025,Animals; Cardiovascular Diseases; Metabolome; ...,Journal Article,NaN,NaN,NaN,https://pubmed.ncbi.nlm.nih.gov/40286622/,2025-12-13 04:03:22
2,Association between air pollution and cardiova...,Long-term exposure to air pollution significan...,"Yan, Chunyu; Chen, Guang; Jing, Yingyu; Ruan, ...","Department of Endocrinology and Metabolism, Xi...",China,Diabetology & metabolic syndrome,2025,NaN,Journal Article,NaN,NaN,NaN,https://pubmed.ncbi.nlm.nih.gov/39980049/,2025-12-13 04:03:16
3,Long-Term Exposure to Air Pollution and Incide...,Research has detected associations between air...,"Fiffer, Melissa R; Chen, Jie; Silva, Emily L; ...","Children's Environmental Health Initiative, Un...",United States,Environmental health perspectives,2025,"Humans; Diabetes Mellitus, Type 2; Female; Air...",Journal Article,NaN,NaN,NaN,https://pubmed.ncbi.nlm.nih.gov/40314697/,2025-12-13 04:03:16
4,Association between exposure to ambient air po...,Air pollution is a recognized contributor to m...,"Wang, Zhe; Ji, Weidong; Wang, Yushan; Li, Lin;...","Zhongshan School of Medicine, Sun Yat-sen Univ...",China,Ecotoxicology and environmental safety,2025,Metabolic Syndrome; Humans; Air Pollutants; Ma...,Journal Article,NaN,NaN,NaN,https://pubmed.ncbi.nlm.nih.gov/39674022/,2025-12-13 04:03:22

# merging all dataset

In [ ]:
df_chronic = pd.read_csv("chronic disease.csv",  header=0, index_col=0)

In [ ]:

def clean_text(text):
    if pd.isna(text):
        return ""
    return str(text).lower().strip()

df_chronic['title_clean'] = df_chronic['Title'].apply(clean_text)
df_chronic['abstract_clean'] = df_chronic['Abstract'].apply(clean_text)

duplicates = df_chronic[
   df_chronic.duplicated(subset=['title_clean'], keep=False) |
    df_chronic.duplicated(subset=['abstract_clean'], keep=False)
]

print("Total duplicate rows found:", duplicates.shape[0])

df_chronic_deduplicated = df_chronic.loc[
    ~(
        df_chronic.duplicated(subset=['title_clean'], keep='first') |
        df_chronic.duplicated(subset=['abstract_clean'], keep='first')
    )
]

print("Rows before deduplication:", df_chronic.shape[0])
print("Rows after deduplication:", df_chronic_deduplicated.shape[0])

df_chronic_deduplicated = df_chronic_deduplicated.drop(
    columns=['title_clean', 'abstract_clean']
)



df_chronic_deduplicated.head()

Total duplicate rows found: 494
Rows before deduplication: 3739
Rows after deduplication: 3253

,Title,Abstract,Authors,Affiliation,Country,Journal,Year,Keywords,Study_Type,Funding,DOI,PMC_ID,URL,Timestamp
PMID,,,,,,,,,,,,,,
41093669,"Corrigendum to ""Mortality risk of short-term a...",NaN,"Liu, Yunning; Xu, Hongbing; Shan, Xuyang; Guan...",National Center for Chronic and Noncommunicabl...,China,International journal of hygiene and environme...,2026,NaN,Published Erratum,NaN,NaN,NaN,https://pubmed.ncbi.nlm.nih.gov/41093669/,2025-12-12 08:48:15
41276395,Radiation Safety in Chronic Total Occlusion Pe...,Chronic total occlusion percutaneous coronary ...,"Devkota, Lorna; Razzouk, Louai; Rao, Sunil V","Department of Internal Medicine, New York Univ...",United States,Interventional cardiology clinics,2026,Humans; Percutaneous Coronary Intervention; Co...,Journal Article; Review,NaN,NaN,NaN,https://pubmed.ncbi.nlm.nih.gov/41276395/,2025-12-12 08:48:09
41275905,Exposure to per- and polyfluoroalkyl substance...,Per- and polyfluoroalkyl substances (PFAS) and...,"Rahman, Humairat H; Stokey, Weston R; Munson-M...","New Mexico State University, Las Cruces, NM, 8...",United States,Food and chemical toxicology : an internationa...,2026,Humans; Phthalic Acids; Glomerular Filtration ...,Journal Article,NaN,NaN,NaN,https://pubmed.ncbi.nlm.nih.gov/41275905/,2025-12-12 08:47:55
41092927,Global age-sex-specific all-cause mortality an...,"Comprehensive, comparable, and timely estimate...",GBD 2023 Demographics Collaborators,NaN,NaN,"Lancet (London, England)",2025,Humans; Life Expectancy; Male; Female; Global ...,Journal Article,NaN,NaN,NaN,https://pubmed.ncbi.nlm.nih.gov/41092927/,2025-12-12 08:48:18
39870131,The role of miRNAs in the associations between...,Epidemiological studies have reported that atm...,"Li, Tiezheng; Xu, Lisha; Shen, Peng; Qiu, Jie;...","Department of Public Health, and Department of...",China,"Environmental pollution (Barking, Essex : 1987)",2025,Humans; MicroRNAs; Particulate Matter; Case-Co...,Journal Article,NaN,NaN,NaN,https://pubmed.ncbi.nlm.nih.gov/39870131/,2025-12-12 08:48:04

In [ ]:
df = pd.concat([df_deduplicated, df_lung_deduplicated, df_heart_deduplicated, df_diabetes_deduplicated, df_chronic_deduplicated], ignore_index=True)

In [ ]:

duplicate_rows = df.duplicated(subset=['Title', 'Abstract'], keep=False)

num_duplicates = duplicate_rows.sum()

print("Number of duplicate rows based on title AND abstract:", num_duplicates)

duplicates_df = df[duplicate_rows]
duplicates_df.head()

Number of duplicate rows based on title AND abstract: 8145

,Title,Abstract,Authors,Affiliation,Country,Journal,Year,DOI,URL,Keywords,Study_Type,Funding,PMC_ID,Timestamp
26,Smoking cessation in India: A narrative review.,Tobacco is the leading preventable cause of de...,Singh Anubhuti; Kishore Kislay,"Department of Respiratory Medicine, Bharati Vi...",India,Lung India : official organ of Indian Chest So...,2025,NaN,https://pubmed.ncbi.nlm.nih.gov/41129577/,NaN,NaN,NaN,NaN,NaN
81,Acute air pollution exposure and gastrointesti...,Gastrointestinal (GI) cancers account for 43.1...,Wu Zhuchao; Wei Chaohua; Sun Jian; Qiu Beibei;...,"School of Public Health and Management, Jiangs...",United States,Frontiers in public health,2025,NaN,https://pubmed.ncbi.nlm.nih.gov/41080867/,NaN,NaN,NaN,NaN,NaN
98,Air Pollution and Effects of Tropospheric Ozon...,Air pollution is a significant and widespread ...,Vongelis Pavlos; Koulouris Nikolaos G; Bakakos...,"Respiratory Function Laboratory, 1st Departmen...",NaN,International journal of environmental researc...,2025,NaN,https://pubmed.ncbi.nlm.nih.gov/40427825/,NaN,NaN,NaN,NaN,NaN
118,Combining International Standards to Develop C...,Smoking is associated with severe health conse...,Thayer Jeritt G; Jenssen Brian P; Fiks Alexand...,Department of Biomedical and Health Informatic...,United States,Journal of medical Internet research,2025,NaN,https://pubmed.ncbi.nlm.nih.gov/41191873/,NaN,NaN,NaN,NaN,NaN
139,[Wildfires and their respiratory impact].,"Largely due to climate change, wildland fires ...",Charpin D; Brun O,Association pour la prévention de la pollution...,France,Revue des maladies respiratoires,2025,NaN,https://pubmed.ncbi.nlm.nih.gov/40044532/,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.shape

(118508, 16)

In [ ]:
import pandas as pd

duplicates = df[
    df.duplicated(subset=['title_clean'], keep=False) |
    df.duplicated(subset=['abstract_clean'], keep=False)
]

print("Total duplicate rows found:", duplicates.shape[0])

df_deduplicated = df.loc[
    ~(
        df.duplicated(subset=['title_clean'], keep='first') |
        df.duplicated(subset=['abstract_clean'], keep='first')
    )
]

print("Rows before deduplication:", df.shape[0])
print("Rows after deduplication:", df_deduplicated.shape[0])

df_deduplicated = df_deduplicated.drop(
    columns=['title_clean', 'abstract_clean']
)

df_deduplicated.to_csv("deduplicated_dataset.csv", index=False)

df_deduplicated.head()

Total duplicate rows found: 53856
Rows before deduplication: 118508
Rows after deduplication: 64653

,Title,Abstract,Authors,Affiliation,Country,Journal,Year,DOI,URL,Keywords,Study_Type,Funding,PMC_ID,Timestamp
0,"Comprehensive study of radon levels, health ri...",Water quality assessment represents a fundamen...,Mohammad Qadr Hiwa; Farhad Salih Najeba; Amin ...,"Department of Physics, College of Science, Uni...",NaN,Regulatory toxicology and pharmacology : RTP,2026,NaN,https://pubmed.ncbi.nlm.nih.gov/41077261/,NaN,NaN,NaN,NaN,NaN
1,Participatory science to action: Radon literac...,Low radon testing rates in communities of colo...,Dai Dajun; Jelks Na'Taki Osborne; Smith Gwendy...,"Department of Geosciences, Georgia State Unive...",Usa,Journal of environmental radioactivity,2026,NaN,https://pubmed.ncbi.nlm.nih.gov/41130130/,NaN,NaN,NaN,NaN,NaN
2,Evaluating overestimated radon risk in predict...,Radon is recognised as the second most signifi...,Tejado-Ramos Juan-José; Alvarez-Toral Aitor; G...,Technological Institute of Ornamental Rocks an...,Spain,Journal of environmental radioactivity,2026,NaN,https://pubmed.ncbi.nlm.nih.gov/41187632/,NaN,NaN,NaN,NaN,NaN
3,The diagnostic potential of urinary volatile o...,Post-colonoscopy colorectal cancer (CRC) rates...,van Liere Elsa L S A; Ramsoekh Dewkoemar; Stew...,"Department of Gastroenterology and Hepatology,...",Uk,International journal of cancer,2026,NaN,https://pubmed.ncbi.nlm.nih.gov/40985860/,NaN,NaN,NaN,NaN,NaN
4,Organ-level radiation dose estimations from ca...,Children with congenital heart disease (CHD) u...,Wong-Siegel Jeannette R; Glatz Andrew C; Zampi...,New York-Presbyterian Morgan Stanley Children'...,NaN,"Radiation physics and chemistry (Oxford, Engla...",2026,NaN,https://pubmed.ncbi.nlm.nih.gov/40756629/,NaN,NaN,NaN,NaN,NaN